spotify/dh-virtualenv

doc/tutorial.rst
The tutorial documentation instructs to use python2.x-minimal in the
binary package Pre-Depends. That raise a lintian error for me:
E: zuul: depends-on-python-minimal pre-depends
The python-minimal package (and versioned variants thereof) exists
only to possibly become an Essential package. Depending on it is
always an error since it should never be installed without python.
If it becomes Essential, there is no need to depend on it, and until
then, packages that require Python must depend on python.
In the tutorial, replace Pre-Depends python2.x-minimal with python2.x.
=> doc: no python2.x-minimal per lintian

doc/info.rst, doc/usage.rst, lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm
Honor ``DH_VIRTUALENV_INSTALL_ROOT`` in build system so that one can override the destination path the same way as with the sequencer approach. I also introduced a new variable ``DH_VIRTUALENV_ARGUMENTS`` to allow overriding virtualenv arguments, e.g. to be able to create non-symlinked packages by passing ``--always-copy`` to virtualenv.
Is that something you'd want to integrate?
There will be conflicts https://github.com/spotify/dh-virtualenv/pull/87. I can update/rebase this pull request if you want to merge that one first.
=> Override build system settings with environment variables

dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/usage.rst
I work with an environment where the venv needs to follow existing naming conventions, and the path $DH_VIRTUALENV_INSTALL_ROOT/[packagename] does not comply.
This patch allows the user to do the following:
```
export DH_VIRTUALENV_INSTALL_ROOT=/srv/www/app/
binary:
[snip]
dh_virtualenv --install-suffix=venv
```
and the resulting venv should be /srv/www/app/venv/
=>  - Added option to specify a custom suffix for the installation path instead of the package name

dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/usage.rst
I work with an environment where the virtualenv only contains dependencies for the application, the actual application code is deployed separately. 
This change allows the user to specify --dependencies-only - this results in no action being taken by deploy.install_package()
=>  - Added option to only install dependencies for packages where only a virtualenv containing dependencies is required

dh_virtualenv/deployment.py
This removes an apparently incorrect special case for Python 3(.4) built-in venv. Trying `--with=python-virtualenv` and `--builtin-venv --python /usr/bin/python3.4` on Debian Jessie, I found that 1) `local/bin/pip` was actually `bin/pip`, and 2) pip wrapper's shebang was too long without calling it through `python`command. Just removing the special case fixed both problems.
=> Fix pip path for Python 3 built-in venv

lib/Debian/Debhelper/Sequence/python_virtualenv.pm
This is to ensure a consistent environment from the 1st and nth install
of a package - currently `invoke-rc.d daemon start` is called before we
have run our interpreter updates.
Signed-off-by: Chris Lamb <chris@chris-lamb.co.uk>
=> Ensure that our venv is configured before we try and start any daemons.

dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/usage.rst
- Add --requirements-filename flag
- use the provided requirements_filename in Deployment
The default is 'requirements.txt', which should be backwards
compatible.
Fixes: #117
=> Allow a explicit filename for 'requirements.txt'

doc/usage.rst, lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm
Buildsystem 
* `DH_REQUIREMENTS_FILE` env var overrides requirements file
* ``DH_PIP_EXTRA_ARGS`` env var adds arguments to ``pip``
* Included basic documentation
#131
=> Buildsystem params

tox.ini
The [tox](https://testrun.org/tox) testing tool automatizes the creation of testing environments for multiple interpreters, making it easier and faster to test dh-virtualenv, as it keeps compatibility back to python2.6.
This change adds a small `tox.ini` file that allows to run all tests for all environments with:
tox
Tox can be easily installed via `pip`:
pip install tox
=> Adds tox configuration for py26/py27 testing

dh_virtualenv/deployment.py, test/test_deployment.py
This change should fix all problems with packaged virtualenvs that where
created using pypy or other non-default interpreter.
It allows multiple alternative python interpreters to be used when
creating a virtualenv by substituting from a list with all known python
interpreter names AFAIK.
Currently the `Deployment.fix_shebangs` only searches and changes
shebangs which are pointing to the default python interpreter
using this regex:
^#!.*bin/\(env \)\?python
This conflicts with virtualenvs created using a different interpreter
(eg: `pypy`), where virtualenv creates files adding shebangs pointing to
`/path/to/venv/bin/pypy` that don't get rewrited to
`/deployment/path/bin/python` by dh-virtualenv as they should as they don't match the original regular expression.
A possible drawback could …
=> Extend shebang fixing for multiple interpreters

dh_virtualenv/deployment.py, test/test_deployment.py
Fixes #139 
I chose to change the delimiter to a colon since @jhermann pointed out it's less likely to conflict.
=> Escape shebang lines with `re.escape` before passing to sed

.gitignore, dh_virtualenv/__init__.py, dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/info.rst, doc/usage.rst, test/test_cmdline.py, test/test_deployment.py, travis-requirements.txt
pip (nowadays) uses `--index-url` instead of `--pypi-url`. This hopefully reduces confusion
=> Introduce new --index-url to take over --pypi-url

dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/dh_virtualenv.1.rst, doc/usage.rst, test/test_deployment.py
Like --extra-pip-arg it's allow to pass argument to virtualenv not yet supported by dh_virtualenv
Our use case is we have trouble when building on Xenial without internet that's why we need to pass --no-download to virtualenv otherwise the virtualenv from Xenial download pip.
Adding this option allow us to experiment the virtualenv flags to fix the build.
=> Add a --extra-virtualenv-arg

README.md, doc/dh_virtualenv.1.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
=> Convert readthedocs links for their .org -> .io migration for hosted projects

test/test_cmdline.py, test/test_deployment.py
Pretty minor patch, just trying to get familiar with the codebase :)
There isn't an actual problem here, but if the `eq_` assertion had failed, the environment unpatching wouldn't happen.  the `patch.dict` contextmanager ensures it'll get unpatched even in exceptional cases.
=> Use patch.dict to avoid test pollution

dh_virtualenv/deployment.py, test/test_deployment.py
Regex didn't work correctly for a case when path to interpreter was wrapped in quotes (happens when path contains space).
=> Fixed error in fix_shebangs()

README.md, bin/dh_virtualenv, dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/dh_virtualenv.1.rst, doc/info.rst, doc/usage.rst, test/test_cmdline.py, test/test_deployment.py
Sorry for a huge PR, try reviewing comment by comment if possible.
This PR does three major things:
1. Tests are no longer run by default
2. Default installation path is changed
3. Next version will be tagged as 1.0 (YAY!)
=> Preparations to 1.0 release

lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm
Post-pone moving sources into build folder from build to install step. This allows running commands (via `override_dh_auto_build`) inside the source folder after preparing the virtual environment but before moving the package itself into the build folder.
For example, this way I can compile PO files in the source folder (using the virtualenv in the build folder) and let the MANIFEST.in take care of moving the MO files into the build folder during installation.
Does that make sense or am I missing something?
=> Buildsystem: Split venv creation and package installation

doc/usage.rst, lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm
The dh_virtualenv target allows to specify a virtualenv name.
this commits introduce a `DH_VIRTUALENV_NAME` vars.
=> buildsystem: allows to specify a virtualenv name

dh_virtualenv/deployment.py, doc/usage.rst, test/test_deployment.py
Includes doc fix: --upgrade-pip takes no argument
=> Ignore --extra-pip-arg in call for --upgrade-pip (fixes #197)

.travis.yml, dh_virtualenv/deployment.py, test/test_cmdline.py, test/test_deployment.py
While trying to add tests for #201, I ran them on Python 3, out of habit, and found they failed.
The first few commits in this pull request fix the code so that all tests pass on Python 2 and 3.
The last commit adds Python 3.4, 3.5 and 3.6 to the Travis CI config file.
=> Run the tests on Python 3

doc/tutorial.rst
Hi, because of #197, I had to build dh-virtualenv from source on debian jessie. Build failed with: `ImportError: No module named sphinx_rtd_theme`. So I installed that dependency too. Then the build succeeded.
Notice that I installed from jessie backports, don't know if that matters.
=> Added sphinx dependencies to tutorial build docs

autoscripts/postinst-dh-virtualenv
The usage of `$DH_VERBOSE` might trigger *unbound variable* errors when used along with the bash -u flag. This might happen when the script is included in a custom postinst expanding the `#DEBHELPER#` tag.
This can be fixed by providing a default value for `$DH_VERBOSE` (0, disabled) when expanding the variable using bash `${VAR:-}`:
From the docs:  https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html
> ${parameter:-word}
>
>   If parameter is unset or null, the expansion of word is substituted. Otherwise, the value of parameter is substituted.
This was making our custom postinst scripts to fail, which we bypassed temporarily by declaring `DH_VIRTUALENV=0` before the `#DEBHELPER#` tag.
=> Make postinst compatible with -u flag

doc/usage.rst, lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm
I found that I could only install `pandas` for a python 3 project by using `pip3` instead of `pip`, so here is rudimentary support for using a configurable pip executable.
=> Environment variable for custom pip executable

bin/dh_virtualenv
This prevents issues where the target virtual environment is not correctly setup, resulting in the lack of `sys.path` injection, etc.
I just spent a good few hours wondering why my deployed `.deb` was not setting the paths correctly; it was because I was building the Debian package locally within my *develoment* virtualenv. I'm not sure exactly what this broke (the `postinst` interpreter replacement logic?) but it meant that nothing could be imported as per usual.
(Rebuilding the deb after running `deactivate` immediately fixed it.)
Patch is somewhat blunt, mostly to describe the problem in code.. and it would at least prevent this particular corner case. (It might break your testsuite, mind you.)
=> Disallow building the dh-virtualenv whilst within a virtualenv?

doc/usage.rst
http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#the-standard-domain
=> docs: cmdoption directive is a deprecated alias for the option directive

doc/usage.rst
The man page for pbuilderrc(5) documents the option as USENETWORK,
not USE_NETWORK.
=> docs: Fix reference to pbuilder's USENETWORK option.

dh_virtualenv/deployment.py, doc/usage.rst
Due to Python bug https://bugs.python.org/issue24875 the `venv` module does not install pip and setuptools when `--system-site-package` is used.
This has been fixed [upstream](https://github.com/python/cpython/blob/e42b705188271da108de42b55d9344642170aa2b/Lib/venv/__init__.py#L61) but has not been backported by distribution maintainers.
The accepted fix is to create the virtual environment first without `--system-site-package` allowing pip and setuptools to be installed and then reconfiguring the environment with `--system-site-package` to enable this option. This is also the recommend fix used by users on [Stack Overflow](https://stackoverflow.com/a/40989759/388127).
I recommend fixing this here in a similar way for consistency until the upstream fix has been rolled out. Otherwise …
=> Python3 venv bootstrap pip and setuptools with --system-site-package

debian/control
Make `--builtin-venv` usable in a sensible way.
=> Depends: python3-venv is a valid alternative to python-virtualenv

doc/howtos.rst
I had to add the `--python` flag when packaging a Python3 application. Otherwise, the virtualenv was built with Python2, regardless of build dependencies and triggers.
The option needed to create a Python3 environments when using the squence method (`--with python-virtualenv`) is well-documented through the example projects. It's not explicitly included in the documentation itself, though.
The experimental buildsystem alternative has not been used in any of the showcased projects. While obvious in hindsight, I found myself digging around for a bit to find the proper way of creating a Python3 environment with it.
I suggest that both methods are added to the Python3 cookbook section.
=> Expand Python3 documentation

dh_virtualenv/deployment.py
Previously, these options were only available to the external `virtualenv` tool.
=> Support venv options for builtin venv

.travis.yml, tox.ini
This PR updates support for Python versions. Specifically it adds Python 3.7 and 3.8 to the CI, and drops Python 2.6 ([EOL October 29, 2013](https://www.python.org/dev/peps/pep-0361/#release-schedule)) and Python 3.4 ([EOL March 18, 2019](https://www.python.org/dev/peps/pep-0429/#id4)). This change is needed to fix the builds for #286, since Python 2.6 can not be downloaded.
=> Updating Python support

debian/rules
This change adds support for the nodoc build option,
disabling build steps that generate documentation.
https://www.debian.org/doc/debian-policy/ch-source.html#debian-rules-and-deb-build-options
=> Add support for DEB_BUILD_OPTIONS=nodoc

dev-requirements.txt, dh_virtualenv/deployment.py, test/test_deployment.py, travis-requirements.txt
``--no-site-packages`` is the default since ages, and by now gone, leading to errors when it is added.
**Exterminate!**
cf. #293
=> Remove deprecated / disappeared virtualenv option

Dockerfile, bin/dh_virtualenv, debian/control, debian/rules, dh_virtualenv/debhelper.py
As we all know, python2.7 is out of support, and Debian are removing support for it. In particular, `python-mock` and `python-sphinx` have both been removed from the Debian repositories for `testing` and `unstable`, meaning that it is impossible to satisfy the `Build-Depends` for `dh-virtualenv` on those distributions.
Likewise, Debian are removing support for `debpython` - `dh-python` superceded it a long time ago.
The long and the short of it is that we need to switch `dh-virtualenv` to run under python3 rather than python2. (Note that `dh-virtualenv` will still be able to build other packages to run under python2.)
To get there, we need to do a few things:
1. Fix a tiny python3-incompatibility in `dh-virtualenv`
2. Import `debhelper.py` into the dh-virtualenv tree, since debpython has …
=> Convert to `dh-virtualenv.deb` to python 3

dh_virtualenv/debhelper.py
While dict.keys is a list in Python2 it is a "set-like object" in
Python3. To keep the output invariant when switching to Python3
explicitly convert to a list.
=> debhelper.py: fix minor python3 incompatibility

Dockerfile
* Adds an "opts" build option to allow more compatible builds
(no Sphinx dependencies)
* Installs debhelper 12 on Bionic from backports
* Fixes minor details that allow using the Dockerfile on Windows,
because of...
You are building a Docker image from Windows against a non-Windows
Docker host. All files and directories added to build context will
have '-rwxr-xr-x' permissions. It is recommended to double check
and reset permissions for sensitive files and directories.
Since this is a pure builder image, that is not an actual problem.
=> Fix build of 1.2 on Bionic (ref #306)

dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/changes.rst, doc/usage.rst, test/test_cmdline.py, test/test_deployment.py
The built-in python3 venv has neither '--setuptools',
nor '--verbose' switch.
=> dh_virtualenv/deployment.py: fix virtualenv options

dh_virtualenv/deployment.py, doc/changes.rst, test/test_deployment.py
Some Python scripts only have `#!python` shebang lines. They also need to be fixed to point to the virtualenv.
This PR expands the search to include files with the `#!python` shebang lines and adds sed syntax to rewrite them as well.
Cherry-picked from https://github.com/StackStorm/dh-virtualenv/commit/340be0ec851953532a620959678a440575982806, which cherry-picked https://github.com/StackStorm/dh-virtualenv/commit/bf43b0ae436c8caa67f24d545df8cfca70d3cb9a.
=> Also fix 'python' shebang lines

lib/Debian/Debhelper/Buildsystem/dh_virtualenv.pm
- fix typo in `dh_virtualenv.pm` for `DH_VIRTUALENV_INSTALL_SUFFIX`
=> fix typo in Buildsystem dh_virtualenv.pm for DH_VIRTUALENV_INSTALL_SUFFIX

doc/howtos.rst
When "Architecture: any" is set in debian/control, and Python packages with binary shared libraries are installed, dh_strip and dh_shlibdeps can fail or corrupt shared libraries in those packages.
The documentation already includes an example for skipping libraries individually, this change adds an example to skip everything under "site-packages".
---
I don't know if this is correct, but it seems to work OK for me with packages build and installed under the same arch and Debian version.
Thanks for the great project.
=> Add example for skipping all shared libraries

dh_virtualenv/cmdline.py, doc/changes.rst, test/test_cmdline.py
Only convert `-O--option`  to `--option` if the option is actually known to `dh_virtualenv`. The patch converts options if they are known to the optionparser and otherwise leaves them at with `-O`, effectively ignoring them.
This is intended by debhelper, see [man debhelper](https://manpages.debian.org/testing/debhelper/debhelper.7.en.html):
>        -O=option|bundle
>           This is used by dh(1) when passing user-specified options to all the commands it runs. If the command supports the specified option or option bundle, it will take effect. If the command does not support the option (or any part of an option bundle), it will be ignored.
This fixes various use cases,  e.g. using the dh_virtualenv sequence and a custom build system:
```Makefile
%:
dh $@ --with=python-virtualenv …
```
=> only use -O options if option is supported

dh_virtualenv/cmdline.py, dh_virtualenv/deployment.py, doc/examples.rst, doc/howtos.rst, doc/tutorial.rst
There are small typos in:
- dh_virtualenv/cmdline.py
- dh_virtualenv/deployment.py
- doc/examples.rst
- doc/howtos.rst
- doc/tutorial.rst
Fixes:
- Should read `workstation` rather than `worksatation`.
- Should read `supported` rather than `suported`.
- Should read `released` rather than `relased`.
- Should read `executables` rather than `exectuables`.
- Should read `deprecated` rather than `deprectaed`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos
